{% set name = "tarts" %}
{% set version = "0.0.0a4" %}  # Update this to your current version
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
# 
source:
  path: ..

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - matplotlib
    - pytorch
    - pytorch-lightning
    - pyyaml
    - torchvision
    - astropy
    - pandas
    - gitpython

test:
  requires:
    - python {{ python_min }}
  imports:
    - TARTS
  commands:
    - python -c "import TARTS; print('Package imported successfully')"
    - python -c "from TARTS import NeuralActiveOpticsSys; print('Core package imported successfully')"

about:
  home: https://github.com/PetchMa/TARTS
  license: MIT
  license_file: LICENSE
  summary: "I like tarts"

extra:
  recipe-maintainers:
    - PetchMa
