{% set name = "tarts" %}
{% set version = "0.0.0a7" %}  # Update this to your current version
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PetchMa/TARTS/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - matplotlib-base
    - pytorch
    - pytorch-lightning
    - pyyaml
    - torchvision
    - astropy-base
    - pandas
    - gitpython

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - TARTS
    - TARTS.NeuralActiveOpticsSys
  commands:
    - pip check

about:
  home: https://github.com/PetchMa/TARTS
  license: MIT
  license_file: LICENSE
  summary: "Neural Active Optics System for LSST telescope"

extra:
  recipe-maintainers:
    - PetchMa
