{% set name = "tarts" %}
{% set version = "0.0.0a5" %}  # Update this to your current version

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PetchMa/TARTS/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 44189755bd476d5de1c65a6dc1748454661bc6c9c93adf371f391cf197b85f9b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - matplotlib-base
    - pytorch
    - pytorch-lightning
    - pyyaml
    - torchvision
    - astropy-base
    - pandas
    - gitpython

test:
  requires:
    - python
    - pip
  imports:
    - TARTS
    - TARTS.NeuralActiveOpticsSys
  commands:
    - pip check

about:
  home: https://github.com/PetchMa/TARTS
  license: MIT
  license_file: LICENSE
  summary: "Neural Active Optics System for LSST telescope"

extra:
  recipe-maintainers:
    - PetchMa
