{% set name = "tarts" %}
{% set version = "0.0.0a1" %}  # Update this to your current version

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PetchMa/TARTS/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 99efa821d49d5997ad0956b9a15ddf2caa89cc1fdcf2fbcb27a9dd15f67c5e56

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    # add runtime dependencies here, e.g., numpy, etc.

test:
  requires:
    - python {{ python_min }}
  imports:
    - tarts

about:
  home: https://github.com/PetchMa/TARTS
  license: MIT
  license_file: LICENSE
  summary: "I like tarts"

extra:
  recipe-maintainers:
    - PetchMa
